version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak
    command: "start --optimized --https-certificate-file=cert.pem --https-certificate-key-file=key.pem"
#    ports:
#      - 8080:8080
    env_file:
      - .env
#    depends_on:
#      - postgres
    networks:
      - keycloak_network
      - proxy_network

#  postgres:
#    image: postgres
#    environment:
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#    volumes:
#      - ./data:/var/lib/postgresql/data
#    networks:
#      - keycloak_network

networks:
  keycloak_network:
  proxy_network:
    external:
      name: utility-infrastructure_default
